- name: Ansible remote shell
  hosts: server
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup: 
        name: ansible_rg1
        location: eastus
      register: rg
    - debug:
        var: rg
